package com.example._CWK40Solution.clean.infrastructure.config.db.schemas;

import com.example._CWK40Solution.clean.entities.Product.Model.Product;
import com.example._CWK40Solution.clean.infrastructure.Product.validation.UniqueProductName;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "Products")
public class ProductSchema extends AbstractEntitySchema<Long> {

    @UniqueProductName(message = "{Unique.product.name}")
    @NotBlank
    @Column(length = 20, unique = true)
    private String name;

    public ProductSchema(String name) {
        this.name = name;
    }

    public ProductSchema(){}

    public ProductSchema(Long id, String name) {
        this.setId(id);
        this.name = name;
    }

    public ProductSchema(Product product){
        this.setId(product.getId());
        this.name = product.getName();
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Product toProduct() {
        Product product = new Product(
                this.getName()
        );
        product.setId(this.getId()); // transform the schema id (generated by database) to entity customer id
        return product;
    }

}
